language: java

jdk: oraclejdk8

sudo: false

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo apt-get update

install: true

script:
  - mvn test -U -X

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
