sudo: required

branches:
  only: 
    - master

services:
  - docker

language: java

jdk:
  - oraclejdk8

script:
  - mvn -m test -X

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
