info:
  build:
    version: ${project.version}
    name: ${project.name}
server:
  port: 8081

# Default profile
spring:
  profiles:
    active: local

security:
  basic:
    enabled: false
  management:
    security:
      enabled: false
      
api:
  region:
    name: TeamPartner
